name: CI-Tests
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:

  Test-Setup:
    name: Test-Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n-chunks: [5]
    outputs:
      n-chunks: ${{ matrix.n-chunks }}
      chunks: ${{ steps.set-test-ids.outputs.chunks }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: set-test-ids
        uses: ./.github/actions/set-test-ids
        with:
          n-chunks: ${{ matrix.n-chunks }}

  AppleM-CMake:
    needs: Test-Setup
    timeout-minutes: 150

    name: AppleM-CMake (chunk ${{ matrix.chunk }})

    strategy:
      fail-fast: false
      matrix:
        chunk: ${{ fromJSON(needs.Test-Setup.outputs.chunks) }}

    runs-on: macos-14

    steps:
    - name: Select XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: checkout
      uses: actions/checkout@v4

    - name: install-deps
      run: sh/setup/install_macos_arm_deps.sh

    - name: cmake-test-64bit
      uses: ./.github/actions/cmake-test
      with:
        cmake-flags: -DSOUFFLE_DOMAIN_64BIT=ON -DSOUFFLE_TEST_EXAMPLES=ON -DSOUFFLE_TEST_THREADS=8
        n-chunks: ${{ needs.Test-Setup.outputs.n-chunks }}
        chunk: ${{ matrix.chunk }}

