name: Populate dependencies

on:
    push:
        branches: [ master ]
    workflow_dispatch:
    pull_request:

permissions:
    contents: write

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Checkout vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git -- 8f3e8d6e95c7f91edea60c47a7d1414ab5ca9492

    - name: Bootstrap vcpkg
      working-directory: vcpkg
      run: ./bootstrap-vcpkg.sh

    # This will execute a dry-run, meaning that libraries will not be built and
    # installed, but they will still be reported to the GitHub dependency graph.
    # This step assumes `vcpkg` has been bootstrapped (run `./vcpkg/bootstrap-vcpkg`)
    - name: Run vcpkg
      run: ${{ github.workspace }}/vcpkg/vcpkg install --dry-run

